version: "3.8"
services:
  # Grafana Provisioner (Go-приложение из Git)
    grafana-provisioner:
        container_name: grafana-provisioner
        build:
            dockerfile: Dockerfile
        environment:
            CONFIG_PATH: config.yaml
            GF_ADMIN_TOKEN: ${GF_ADMIN_TOKEN}
            METRICS_DB_PASSWORD: ${METRICS_DB_PASSWORD}