{
 "title": "Elmon-test",
 "description": "Elmon Postgre SQL servers monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "select server_id as __value, name as __text from server"
   }
  ]
 },
 "panels": [
  { "title": "perfomance - general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "server",
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: center; height: 100%;\">\r\n<h1>${server:text}</h1>\r\n</div>\r\n"
   }
  },
  {
   "title": "uptime - $server",
   "type": "stat",
   "description": "server uptime",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "select mv.\"time\" as time \r\n\t, (metric_value ->> 'value')::float as value\r\nfrom metric_value mv \r\ninner join metric m on m.metric_id  = mv.metric_id \r\nwhere m.metric_name = 'db_uptime'\r\n    and mv.server_id = $server  -- Используем ID из переменной\r\n    and time between $__timeFrom() and $__timeTo()\r\norder by mv.\"time\""
    }
   ]
  },
  {
   "title": "TPS - $server",
   "type": "stat",
   "description": "total transactions",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "repeat": "server",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "WITH metric_data AS (\r\n  SELECT\r\n    mv.\"time\" AS time,\r\n    (metric_value ->> 'value')::float AS value\r\n  FROM metric_value mv\r\n  INNER JOIN metric m ON m.metric_id = mv.metric_id\r\n  WHERE\r\n    m.metric_name = 'total_transactions'\r\n    AND mv.server_id = $server\r\n    AND time BETWEEN $__timeFrom() AND $__timeTo()\r\n),\r\ntime_diff AS (\r\n  SELECT\r\n    time,\r\n    value - LAG(value, 1) OVER (ORDER BY time) AS value_diff,\r\n    EXTRACT(EPOCH FROM (time - LAG(time, 1) OVER (ORDER BY time))) AS seconds_diff\r\n  FROM metric_data\r\n)\r\nSELECT\r\n  time,\r\n  value_diff / NULLIF(seconds_diff, 0) AS value -- 'value' is our TPS\r\nFROM time_diff\r\nWHERE\r\n  value_diff >= 0 AND seconds_diff > 0\r\nORDER BY\r\n  time"
    }
   ]
  },
  {
   "title": "cache_hit_ratio - $server",
   "type": "stat",
   "description": "cache hit ratio",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "repeat": "server",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "select mv.\"time\" as time \r\n\t, (metric_value ->> 'value')::float as value\r\nfrom metric_value mv \r\ninner join metric m on m.metric_id  = mv.metric_id \r\nwhere m.metric_name = 'cache_hit_ratio'\r\n    and mv.server_id = $server  -- Используем ID из переменной\r\n    and time between $__timeFrom() and $__timeTo()\r\norder by mv.\"time\""
    }
   ]
  },
  {
   "title": "avg_duration - $server",
   "type": "stat",
   "description": "avg statements duration",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "with cte_total as (\r\n\tselect mv.\"time\" \r\n\t\t,   (metric_value -> 'select' ->> 'total_time_ms')::float\r\n\t\t  + (metric_value -> 'insert' ->> 'total_time_ms')::float\r\n\t\t  + (metric_value -> 'update' ->> 'total_time_ms')::float\r\n\t\t  + (metric_value -> 'delete' ->> 'total_time_ms')::float\r\n\t\t  + (metric_value -> 'ddl' ->> 'total_time_ms')::float\r\n\t\t  + (metric_value -> 'other' ->> 'total_time_ms')::float  as total_time_ms\r\n\t\t,   (metric_value -> 'select' ->> 'execution_count')::bigint\r\n\t\t  + (metric_value -> 'insert' ->> 'execution_count')::bigint\r\n\t\t  + (metric_value -> 'update' ->> 'execution_count')::bigint\r\n\t\t  + (metric_value -> 'delete' ->> 'execution_count')::bigint\r\n\t\t  + (metric_value -> 'ddl' ->> 'execution_count')::bigint\r\n\t\t  + (metric_value -> 'other' ->> 'execution_count')::bigint as execution_count\r\n\tfrom metric_value mv \r\n\tinner join metric m on m.metric_id  = mv.metric_id \r\n\twhere m.metric_name = 'total_execution_time'\r\n    and mv.server_id = $server  -- Используем ID из переменной\r\n    and time between $__timeFrom() and $__timeTo()\r\n)\r\n, cte_delta as (\r\n\tselect time\r\n\t\t, total_time_ms - lag(total_time_ms, 1) over (order by time) delta_time_ms\r\n\t\t, execution_count - lag(execution_count, 1) over (order by time) delta_count\r\n\tfrom cte_total\r\n\torder by \"time\" desc\r\n)\r\nselect time\r\n\t , delta_time_ms / delta_count as value\r\nfrom cte_delta \r\nwhere delta_count <> 0\r\norder by \"time\" desc"
    }
   ]
  },
  {
   "title": "active_tx - $server",
   "type": "stat",
   "description": "active transactions count",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "select time\r\n\t , (mv.metric_value ->> 'active'):: bigint as value \r\nfrom metric_value mv \r\ninner join metric m on m.metric_id  = mv.metric_id \r\nwhere m.metric_name = 'connection_count'\r\n    and mv.server_id = $server  -- Используем ID из переменной\r\n    and time between $__timeFrom() and $__timeTo()\r\norder by mv.\"time\""
    }
   ]
  },
  {
   "title": "lock_waits - $server",
   "type": "stat",
   "description": "count of lock waits",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "select mv.\"time\" as time \r\n\t, (metric_value ->> 'value')::float as value\r\nfrom metric_value mv \r\ninner join metric m on m.metric_id  = mv.metric_id \r\nwhere m.metric_name = 'wait_locks'\r\n    and mv.server_id = $server  -- Используем ID из переменной\r\n    and time between $__timeFrom() and $__timeTo()\r\norder by mv.\"time\""
    }
   ]
  },
  { "title": "Maitenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } }
 ]
}